export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const SET_EMAIL_ERROR = "SET_PASSWORD_ERROR";
export const SET_BIRTHDAY_ERROR = "SET_BIRTHDAY_ERROR";
export const CLEAR_EMAIL_ERROR = "CLEAR_EMAIL_ERROR";
export const CLEAR_BIRTHDAY_ERROR = "CLEAR_BIRTHDAY_ERROR";
